/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    pages: Page;
    services: Service;
    staff: Staff;
    specialties: Specialty;
    forms: Form;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    specialties: SpecialtiesSelect<false> | SpecialtiesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'header-options': HeaderOption;
    'footer-options': FooterOption;
    options: Option;
    'seo-options': SeoOption;
  };
  globalsSelect: {
    'header-options': HeaderOptionsSelect<false> | HeaderOptionsSelect<true>;
    'footer-options': FooterOptionsSelect<false> | FooterOptionsSelect<true>;
    options: OptionsSelect<false> | OptionsSelect<true>;
    'seo-options': SeoOptionsSelect<false> | SeoOptionsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  folder: 'first' | 'right';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  keywords?: string[] | null;
  layout?:
    | (
        | {
            variant?: ('default' | 'service' | 'custom') | null;
            img?: (number | null) | Media;
            logo?: (number | null) | Media;
            beforeHeading?: string | null;
            heading: string;
            thesis?: string | null;
            price?: string | null;
            old_price?: string | null;
            description?: string | null;
            actions?:
              | {
                  name: string;
                  icon?: ('clipboard-list' | 'cog' | 'instagram' | 'headhunter') | null;
                  variant?: ('default' | 'icon' | 'icon-text') | null;
                  color?: ('primary' | 'accent' | 'secondary' | 'white' | 'red') | null;
                  action?: ('link' | 'form') | null;
                  url?: string | null;
                  form?: (number | null) | Form;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            img?: (number | null) | Media;
            heading: string;
            description: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founder';
          }
        | {
            heading: string;
            description: string;
            advantages?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            main?: (number | null) | Service;
            services: {
              service: number | Service;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            beforeHeading?: string | null;
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            img?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'installment';
          }
        | {
            advantages: {
              img?: (number | null) | Media;
              heading: string;
              description?: string | null;
              advantages?:
                | {
                    heading: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            challenges: {
              img?: (number | null) | Media;
              heading: string;
              description?: string | null;
              challenges?:
                | {
                    heading: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages-challenges';
          }
        | {
            indications?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            contraindications?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'indications-contraindications';
          }
        | {
            heading: string;
            description: string;
            methods?:
              | {
                  img?: (number | null) | Media;
                  heading: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methods';
          }
        | {
            heading: string;
            description: string;
            stages?:
              | {
                  heading: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stages';
          }
        | {
            heading: string;
            description: string;
            services?:
              | {
                  item: number | Service;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-cost';
          }
        | {
            heading: string;
            description: string;
            photos?:
              | {
                  beforeImg: number | Media;
                  afterImg: number | Media;
                  heading: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'works-photos';
          }
        | {
            staff: number | Staff;
            id?: string | null;
            blockName?: string | null;
            blockType: 'staff';
          }
        | {
            blockHeading?: string | null;
            img?: (number | null) | Media;
            heading: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            heading: string;
            experts: (number | Staff)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'expert-team';
          }
        | {
            heading: string;
            description: string;
            images?:
              | {
                  img: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            description?: string | null;
            certificates?:
              | {
                  img: number | Media;
                  doc: number | Document;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cert-list';
          }
        | {
            heading: string;
            items?:
              | {
                  icon?: ('clipboard-list' | 'cog' | 'instagram' | 'headhunter') | null;
                  heading: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-are-we';
          }
        | {
            img?: (number | null) | Media;
            heading: string;
            description: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'history';
          }
        | {
            staff: number | Staff;
            quote?: string | null;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gbt-hello';
          }
        | {
            items?:
              | {
                  heading: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'what-do-your-get';
          }
        | {
            img: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            video: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            heading?: string | null;
            description?: string | null;
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            folder: 'first' | 'right';
            id?: string | null;
            blockName?: string | null;
            blockType: 'documents';
          }
        | {
            heading: string;
            description: string;
            showOnlyPositive?: boolean | null;
            /**
             * Вставьте код iframe с отзывами из Яндекс.Карт
             */
            yandexIframeCode?: string | null;
            /**
             * Вставьте код iframe с отзывами из 2ГИС
             */
            twoGisIframeCode?: string | null;
            videoReviews?:
              | {
                  title: string;
                  /**
                   * Ссылка на видео (YouTube, Vimeo и т.д.)
                   */
                  videoUrl: string;
                  /**
                   * Изображение превью для видео
                   */
                  thumbnail?: (number | null) | Media;
                  author?: string | null;
                  /**
                   * Фото пациента для отображения в отзыве
                   */
                  avatar?: (number | null) | Media;
                  /**
                   * Например: Имплантация, Отбеливание зубов
                   */
                  procedure?: string | null;
                  /**
                   * Оценка от 1 до 5 звезд
                   */
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            description: string;
            included?:
              | {
                  icon?: ('clipboard-list' | 'cog' | 'instagram' | 'headhunter') | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            price: string;
            old_price?: string | null;
            motivation?: string | null;
            features?: string[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gbt-subscribe';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  form_id: string;
  webhook?: string | null;
  heading: string;
  description?: string | null;
  fields?:
    | {
        name: string;
        type: 'text' | 'textarea' | 'number' | 'checkbox' | 'select';
        label?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        placeholder?: string | null;
        required?: boolean | null;
        textOptions?: {
          validation?: ('off' | 'phone' | 'email' | 'url') | null;
          minLength?: number | null;
          maxLength?: number | null;
        };
        numberOptions?: {
          min?: number | null;
          max?: number | null;
        };
        selectOptions?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  img?: (number | null) | Media;
  title: string;
  url?: string | null;
  description?: string | null;
  advantages?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  price?: string | null;
  old_price?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  img: number | Media;
  fullname: string;
  experience: number;
  description?: string | null;
  specialty: (number | Specialty)[];
  alternativeSpecialty?: string | null;
  staffPage?: (number | null) | Page;
  bookingLink?: string | null;
  features?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties".
 */
export interface Specialty {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'specialties';
        value: number | Specialty;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  keywords?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              img?: T;
              logo?: T;
              beforeHeading?: T;
              heading?: T;
              thesis?: T;
              price?: T;
              old_price?: T;
              description?: T;
              actions?:
                | T
                | {
                    name?: T;
                    icon?: T;
                    variant?: T;
                    color?: T;
                    action?: T;
                    url?: T;
                    form?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founder?:
          | T
          | {
              img?: T;
              heading?: T;
              description?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              heading?: T;
              description?: T;
              advantages?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              main?: T;
              services?:
                | T
                | {
                    service?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              beforeHeading?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        installment?:
          | T
          | {
              img?: T;
              id?: T;
              blockName?: T;
            };
        'advantages-challenges'?:
          | T
          | {
              advantages?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    advantages?:
                      | T
                      | {
                          heading?: T;
                          description?: T;
                          id?: T;
                        };
                  };
              challenges?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    challenges?:
                      | T
                      | {
                          heading?: T;
                          description?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'indications-contraindications'?:
          | T
          | {
              indications?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              contraindications?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        methods?:
          | T
          | {
              heading?: T;
              description?: T;
              methods?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stages?:
          | T
          | {
              heading?: T;
              description?: T;
              stages?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-cost'?:
          | T
          | {
              heading?: T;
              description?: T;
              services?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'works-photos'?:
          | T
          | {
              heading?: T;
              description?: T;
              photos?:
                | T
                | {
                    beforeImg?: T;
                    afterImg?: T;
                    heading?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        staff?:
          | T
          | {
              staff?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              blockHeading?: T;
              img?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'expert-team'?:
          | T
          | {
              heading?: T;
              experts?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              description?: T;
              images?:
                | T
                | {
                    img?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cert-list'?:
          | T
          | {
              heading?: T;
              description?: T;
              certificates?:
                | T
                | {
                    img?: T;
                    doc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-are-we'?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        history?:
          | T
          | {
              img?: T;
              heading?: T;
              description?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        'gbt-hello'?:
          | T
          | {
              staff?: T;
              quote?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'what-do-your-get'?:
          | T
          | {
              items?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              img?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              video?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              description?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        documents?:
          | T
          | {
              folder?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              heading?: T;
              description?: T;
              showOnlyPositive?: T;
              yandexIframeCode?: T;
              twoGisIframeCode?: T;
              videoReviews?:
                | T
                | {
                    title?: T;
                    videoUrl?: T;
                    thumbnail?: T;
                    author?: T;
                    avatar?: T;
                    procedure?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'gbt-subscribe'?:
          | T
          | {
              description?: T;
              included?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              price?: T;
              old_price?: T;
              motivation?: T;
              features?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  img?: T;
  title?: T;
  url?: T;
  description?: T;
  advantages?:
    | T
    | {
        title?: T;
        id?: T;
      };
  price?: T;
  old_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  img?: T;
  fullname?: T;
  experience?: T;
  description?: T;
  specialty?: T;
  alternativeSpecialty?: T;
  staffPage?: T;
  bookingLink?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties_select".
 */
export interface SpecialtiesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  form_id?: T;
  webhook?: T;
  heading?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        label?: T;
        placeholder?: T;
        required?: T;
        textOptions?:
          | T
          | {
              validation?: T;
              minLength?: T;
              maxLength?: T;
            };
        numberOptions?:
          | T
          | {
              min?: T;
              max?: T;
            };
        selectOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-options".
 */
export interface HeaderOption {
  id: number;
  navigation?:
    | {
        label: string;
        color?: ('default' | 'accent') | null;
        url?: string | null;
        hasCategories?: boolean | null;
        categories?:
          | {
              label: string;
              url?: string | null;
              hasItems?: boolean | null;
              items?:
                | {
                    label: string;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  actionButtons?:
    | {
        name: string;
        icon?: ('clipboard-list' | 'cog' | 'instagram' | 'headhunter') | null;
        variant?: ('default' | 'icon' | 'icon-text') | null;
        color?: ('primary' | 'accent' | 'secondary' | 'white' | 'red') | null;
        action?: ('link' | 'form') | null;
        url?: string | null;
        form?: (number | null) | Form;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-options".
 */
export interface FooterOption {
  id: number;
  thesis?: string | null;
  services?:
    | {
        page: number | Page;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  warning?: string | null;
  documentLinks?:
    | {
        document: number | Document;
        id?: string | null;
      }[]
    | null;
  actionButtons?:
    | {
        name: string;
        icon?: ('clipboard-list' | 'cog' | 'instagram' | 'headhunter') | null;
        variant?: ('default' | 'icon' | 'icon-text') | null;
        color?: ('primary' | 'accent' | 'secondary' | 'white' | 'red') | null;
        action?: ('link' | 'form') | null;
        url?: string | null;
        form?: (number | null) | Form;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  rights?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options".
 */
export interface Option {
  id: number;
  orgNameShort?: string | null;
  orgNameFull?: string | null;
  addressShort?: string | null;
  addressFull?: string | null;
  ogrn?: string | null;
  inn?: string | null;
  kpp?: string | null;
  okpo?: string | null;
  workTimeStart?: string | null;
  workTimeEnd?: string | null;
  phones?:
    | {
        phone: string;
        hasTelegram: boolean;
        hasWhatsapp: boolean;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        mail: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-options".
 */
export interface SeoOption {
  id: number;
  yandexMetrika?: {
    enabled?: boolean | null;
    /**
     * Введите ID счетчика Яндекс.Метрики
     */
    counterId?: string | null;
    /**
     * Записывает видео сессий пользователей
     */
    webvisor?: boolean | null;
    /**
     * Показывает места кликов на странице
     */
    clickmap?: boolean | null;
    /**
     * Отслеживает переходы по внешним ссылкам
     */
    trackLinks?: boolean | null;
    /**
     * Улучшает точность измерения отказов
     */
    accurateTrackBounce?: boolean | null;
  };
  metaTags?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    defaultKeywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-options_select".
 */
export interface HeaderOptionsSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        color?: T;
        url?: T;
        hasCategories?: T;
        categories?:
          | T
          | {
              label?: T;
              url?: T;
              hasItems?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  actionButtons?:
    | T
    | {
        name?: T;
        icon?: T;
        variant?: T;
        color?: T;
        action?: T;
        url?: T;
        form?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-options_select".
 */
export interface FooterOptionsSelect<T extends boolean = true> {
  thesis?: T;
  services?:
    | T
    | {
        page?: T;
        title?: T;
        id?: T;
      };
  warning?: T;
  documentLinks?:
    | T
    | {
        document?: T;
        id?: T;
      };
  actionButtons?:
    | T
    | {
        name?: T;
        icon?: T;
        variant?: T;
        color?: T;
        action?: T;
        url?: T;
        form?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  rights?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options_select".
 */
export interface OptionsSelect<T extends boolean = true> {
  orgNameShort?: T;
  orgNameFull?: T;
  addressShort?: T;
  addressFull?: T;
  ogrn?: T;
  inn?: T;
  kpp?: T;
  okpo?: T;
  workTimeStart?: T;
  workTimeEnd?: T;
  phones?:
    | T
    | {
        phone?: T;
        hasTelegram?: T;
        hasWhatsapp?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        mail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-options_select".
 */
export interface SeoOptionsSelect<T extends boolean = true> {
  yandexMetrika?:
    | T
    | {
        enabled?: T;
        counterId?: T;
        webvisor?: T;
        clickmap?: T;
        trackLinks?: T;
        accurateTrackBounce?: T;
      };
  metaTags?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}