/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    staff: Staff;
    specialties: Specialty;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    specialties: SpecialtiesSelect<false> | SpecialtiesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    navigation: Navigation;
    globalSettings: GlobalSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    globalSettings: GlobalSettingsSelect<false> | GlobalSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  keywords?: string | null;
  layout?:
    | (
        | {
            variant?: ('default' | 'service' | 'custom') | null;
            img?: (number | null) | Media;
            beforeHeading?: string | null;
            heading: string;
            thesis?: string | null;
            price?: string | null;
            old_price?: string | null;
            description?: string | null;
            actions?:
              | {
                  name: string;
                  icon?: ('clipboard-list' | 'cog' | 'instagram') | null;
                  color?: ('primary' | 'accent' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            img?: (number | null) | Media;
            heading: string;
            description: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founder';
          }
        | {
            heading: string;
            description: string;
            advantages?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            main?: (number | null) | Service;
            count: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            beforeHeading?: string | null;
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'installment';
          }
        | {
            advantages: {
              img?: (number | null) | Media;
              heading: string;
              description?: string | null;
              advantages?:
                | {
                    heading: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            challenges: {
              img?: (number | null) | Media;
              heading: string;
              description?: string | null;
              challenges?:
                | {
                    heading: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages-challenges';
          }
        | {
            indications?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            contraindications?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'indications-contraindications';
          }
        | {
            heading: string;
            description: string;
            methods?:
              | {
                  img?: (number | null) | Media;
                  heading: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methods';
          }
        | {
            heading: string;
            description: string;
            stages?:
              | {
                  heading: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stages';
          }
        | {
            heading: string;
            description: string;
            services?:
              | {
                  item: number | Service;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-cost';
          }
        | {
            heading: string;
            description: string;
            photos?:
              | {
                  beforeImg: number | Media;
                  afterImg: number | Media;
                  heading: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'works-photos';
          }
        | {
            staff: number | Staff;
            id?: string | null;
            blockName?: string | null;
            blockType: 'staff';
          }
        | {
            blockHeading?: string | null;
            img?: (number | null) | Media;
            heading: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            heading: string;
            experts: (number | Staff)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'expert-team';
          }
        | {
            heading: string;
            description: string;
            images?:
              | {
                  img: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?:
              | {
                  icon?: ('clipboard-list' | 'cog' | 'instagram') | null;
                  heading: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-are-we';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  img?: (number | null) | Media;
  title: string;
  url?: string | null;
  description?: string | null;
  advantages?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  price?: string | null;
  old_price?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  img: number | Media;
  fullname: string;
  experience: number;
  description?: string | null;
  specialty: (number | Specialty)[];
  alternativeSpecialty?: string | null;
  staffPage?: (number | null) | Page;
  features?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties".
 */
export interface Specialty {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'specialties';
        value: number | Specialty;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  keywords?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              img?: T;
              beforeHeading?: T;
              heading?: T;
              thesis?: T;
              price?: T;
              old_price?: T;
              description?: T;
              actions?:
                | T
                | {
                    name?: T;
                    icon?: T;
                    color?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founder?:
          | T
          | {
              img?: T;
              heading?: T;
              description?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              heading?: T;
              description?: T;
              advantages?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              main?: T;
              count?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              beforeHeading?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        installment?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'advantages-challenges'?:
          | T
          | {
              advantages?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    advantages?:
                      | T
                      | {
                          heading?: T;
                          description?: T;
                          id?: T;
                        };
                  };
              challenges?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    challenges?:
                      | T
                      | {
                          heading?: T;
                          description?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'indications-contraindications'?:
          | T
          | {
              indications?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              contraindications?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        methods?:
          | T
          | {
              heading?: T;
              description?: T;
              methods?:
                | T
                | {
                    img?: T;
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stages?:
          | T
          | {
              heading?: T;
              description?: T;
              stages?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-cost'?:
          | T
          | {
              heading?: T;
              description?: T;
              services?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'works-photos'?:
          | T
          | {
              heading?: T;
              description?: T;
              photos?:
                | T
                | {
                    beforeImg?: T;
                    afterImg?: T;
                    heading?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        staff?:
          | T
          | {
              staff?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              blockHeading?: T;
              img?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        'expert-team'?:
          | T
          | {
              heading?: T;
              experts?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              description?: T;
              images?:
                | T
                | {
                    img?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-are-we'?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    heading?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  img?: T;
  title?: T;
  url?: T;
  description?: T;
  advantages?:
    | T
    | {
        title?: T;
        id?: T;
      };
  price?: T;
  old_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  img?: T;
  fullname?: T;
  experience?: T;
  description?: T;
  specialty?: T;
  alternativeSpecialty?: T;
  staffPage?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialties_select".
 */
export interface SpecialtiesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        url?: string | null;
        hasCategories?: boolean | null;
        categories?:
          | {
              label: string;
              url?: string | null;
              hasItems?: boolean | null;
              items?:
                | {
                    label: string;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "globalSettings".
 */
export interface GlobalSetting {
  id: number;
  display: {
    thesis: string;
    links?:
      | {
          icon: 'clipboard-list' | 'cog' | 'instagram';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    services?:
      | {
          item?: (number | null) | Service;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        hasCategories?: T;
        categories?:
          | T
          | {
              label?: T;
              url?: T;
              hasItems?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "globalSettings_select".
 */
export interface GlobalSettingsSelect<T extends boolean = true> {
  display?:
    | T
    | {
        thesis?: T;
        links?:
          | T
          | {
              icon?: T;
              url?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        services?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}